haxenme/nme

project/src/sdl2/SDL2Stage.cpp
Tested with 3 simultaneous joypads and deconnection+reconnection scenario. Thanks to Alan McCosh for pointing this out.
=> joystick connection accounting fix

nme/filters/BlurFilter.hx, nme/filters/ColorMatrixFilter.hx, nme/filters/DropShadowFilter.hx
I'm not sure what's was the reason for keeping them private,  since they are writeable and public in Flash API.
I've read the nme implementation and tested the changes and filters behave correctly (new effects are only applied when `.filters` is re-assigned) same as in Flash.
=> Made filters' fields public, to be consistent with Flash API

tools/nme/src/CommandLineTools.hx, tools/nme/src/project/NMEProject.hx
Now debug property on `NMEPRoject` is set through `setDebug` which creates or removes local define.
This will allow to do `if="debug"` and `unless="debug"` in `project.nmml`
=> Add debug to defines so it could be used in nmml file

templates/ios/PROJ.xcodeproj/project.pbxproj, tools/nme/src/platforms/IOSPlatform.hx, tools/nme/src/project/NMEProject.hx, tools/nme/src/project/NMMLParser.hx
This allows me to set the -ObjC flag which is required for haxe-applovin on ios. I also modified project.pbxproj. With the -ObjC flag duplicate symbols will exist unless the ::if (importStatic==""):: is present.
=> Ios other linker flags

nme/events/EventDispatcher.hx
Below code falls into endless cycle: (actionscript like this works well)
function testEventMouse() {
function qqq(evt: MouseEvent) {
trace("*** !!! " + evt.cancelable);
stage.removeEventListener(MouseEvent.MOUSE_UP, qqq);
stage.addEventListener(MouseEvent.MOUSE_UP, qqq);
//evt.stopImmediatePropagation();
}
stage.addEventListener(MouseEvent.MOUSE_UP, qqq);
}
testEventMouse();
=> Problem with event dispatcher

tools/nme/src/platforms/IOSPlatform.hx, tools/nme/src/project/NMMLParser.hx
It looked like the images defined using the launchImage tags in the project file weren't currently being used. This restores this functionality by checking for and copying the file if needed from within createLaunchImage.
=> iOS - restored functionality to define launchImages in project files.

project/src/audio/OpenALSound.cpp
I've made some changes which seemingly fixes #338. I'm absolutely unfamiliar with OpenAL, but it appears that the issue was that on suspend and resume we were looping through the ChannelList (which also contained our old non-GC'd channels) and calling resume on them which was in turn playing them regardless if they were complete or not. 
Given that Sound calls SuspendOpenAl() and ResumeOpenAl() anyway, it seemed to me that the contents of the OpenALSourceChannel suspend() and resume() may be pretty redundant if OpenAL was resumed using alcProcessContext. 
This works well at this end, but obviously I'd recommend you sanity check my reasoning!
=> Fix OpenAL sound resuming

nme/Assets.hx
When a missing asset is encountered, Assets.hx currently prints out a list of all the assets in the project. If you have a lot of assets this is *really* unhelpful because it obscures the actual missing asset error.
=> Remove debug spam when a missing asset is encountered

nme/Vector.hx
I'm working on NME/OpenFL compatibility, with the goal of getting the HaxeFlixel tests passing using both OpenFL and NME. The @:from Array<T> is necessary for Flixel drawTriangles code to compile using nme/flash.
I'm guessing this was historically an abstract even on Flash, because there were some leftover `#if flash` blocks inside the abstract, even though it is currently excluded on Flash.
=> Use abstract for nme.Vector on Flash.

templates/haxe/ApplicationBoot.hx, templates/haxe/ApplicationDocument.hx, templates/haxe/ApplicationMain.hx
Needed for HaxeFlixel test classes. This allows the templates to work with an APP_MAIN class which has no constructor, or one with a `private static function main()`.
=> Template fixes for private main function or no constructor.

project/ToolkitBuild.xml
It was problem with SDL from toolkit.
"mac" not declared and nme didn't compile.
Also on OS X 10.9: Information:clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 Its not issue, maybe for future implementations.
=> Fix ToolkitBuild on Mac

project/src/audio/ChannelList.cpp, project/src/audio/OpenALSound.cpp
The first commit reverts https://github.com/haxenme/nme/commit/534cdd692749d6557a08e215da071249a076b3b6 which causes this regression https://github.com/haxenme/nme/issues/403.
The 2nd commit fixes the issue the first was trying to tackle. If you play a bunch of single sound effects and then minimize and reopen the app on iOS the code in ChannelList will replay sounds already finished.
=> Audio regression and prior issue fixes

tools/nme/src/platforms/AndroidPlatform.hx, tools/nme/src/project/NMEProject.hx, tools/nme/src/project/NMMLParser.hx
Use
`<android addV4Compat="false"/>`
in xml when you want to add your own V4Compat lib. 
addV4Compat is true by default.
Also, added a temporary variable for getAndroidProject (AndroidPlatform.hx line 167) to avoid crash on
my current haxe/hxcpp version, which should have the same behavior but
safer.
Thanks
=> flag for avoid adding V4Compat

tools/nme/src/project/NMMLParser.hx
The flag does not need "!" since it matches the internal addV4Flag. Thanks.
=> fix addV4Compat flag

project/src/sdl2/SDL2Stage.cpp
Sometimes I got a black icon in the task bar. 
This code updates the icon correctly, without having to implement Lib.setIcon() 
Tested on Windows 10.
=> [SDL2 Windows] Fix black icon in Task Bar

nme/JNI.hx
add warning to use "keep" in functuns for onCallback
=> Android: add warning for DLC in JNI onCallback

tools/nme/src/helpers/IconHelper.hx
The rows of ADD masks needs to be aligned to 4 bytes.
Alpha was broken due premultiplyied alpha.
You can check the generated icons with "Icon Browser" https://www.codeproject.com/kb/cs/iconlib.aspx
=> Fix windows icon padding and alpha, more clear

project/src/audio/OpenALSound.cpp
As per #446, this unbinds a sound's buffer from the OpenAL source and then deletes it when a channel is stopped. This seems right to me based on a scan of OpenAL tutorials and going on the fact you zero the ```sourceId``` already, but obviously please sanity check.
This takes the memory use for our example from (with a peak of ~89mb):
To (with a peak of ~8mb):
For reference, the example I was using was:
```
class Main extends nme.display.Sprite {
private var _count:Int = 0;
public function new () {
super();
stage.color = 0x00FF00;
stage.addEventListener(nme.events.Event.ENTER_FRAME, enterFrame);
}
private function enterFrame(e:nme.events.Event):Void {
if (_count++ % 3 == 0) {
var sound:nme.media.Sound = nme.Assets.getSound("assets/Bubble_1_df.ogg", false);
if (sound != null) { …
```
=> Delete underlying OpenAL source when a channel is stopped

nme/text/TextFormatAlign.hx
Probably doesn't make much difference, but changing for OpenFL compatibility. In OpenFL you can have variables of type TextFormatAlign with values such as `TextFormat.LEFT`. This doesn't work with NME since TextFormatAlign is a class but its members are strings.
=> Convert TextFormatAlign to enum abstract.

project/src/sdl2/SDL2Stage.cpp
Use the 16x16 icon on top of the window and taskbar (small icons option on Windows 10), instead of the one of 32x32.  
Related: 
https://blog.barthe.ph/2009/07/17/wmseticon/
http://www.openfl.org/archive/community/bugs/lack-of-16x16-windows-toolbar-icon/
=> [windows sdl2] adjust small icon size

src/nme/app/Window.hx, src/nme/display/Stage.hx
Now "render" and "event" names show correctly on hxScout.  Fix code
indentation.
Issue: https://github.com/haxenme/nme/issues/451
=> hxtelemetry: fix timing names

include.nmml, src/nme/app/Application.hx, src/nme/app/Window.hx, src/nme/display/Stage.hx, templates/haxe/ApplicationMain.hx
Get host and allocations parameters from xml and fix app_name.  
Currently host and allocations are set using "setenv" from xml with names TELEMETRY_HOST and TELEMETRY_ALLOCATIONS ( OpenFL uses a config:hxtelemetry tag ). 
Example:
```
<setenv name="TELEMETRY_HOST" value="localhost"/>
<setenv name="TELEMETRY_ALLOCATIONS" value="true"/>
```
Moved most of telemetry code from Stage.hx to Application.hx. 
Allow `-Dtelemetry` as in OpenFL, as well -DNME_HXTELEMETRY.
=> hxTelemetry parameters from xml

tools/nme/src/platforms/CppiaPlatform.hx, tools/nme/src/platforms/Platform.hx
I think I've really not notice the water boiling on this one. This speeds up my build time by 53.40 seconds! This was happening even with no file changes.
=> Huge build speedup by not generating manifest file.

templates/android/PROJ/src/org/haxe/nme/GameActivity.java
In some cases xdpi and desityDpi the same. On my android tv 7.1.1 I have 240 but this method return me xdpi value 68 and my content looks small.
=> fix android screen DPI

project/ToolkitBuild.xml, project/src/common/ExternalInterface.cpp, project/src/winrt/Main.cpp, tools/nme/src/platforms/WinrtPlatform.hx
winrt needed to find nme_managed_stage_create from ExternalInterface at startup.
Fixes compile error 'FALSE': undeclared identifier
Included a NME_NO_LZMA define as NME_NO_CURL and NME_NO_CAMERA. These are practical for considering (*) other targets.  Furthermore, could be considered later for custom functionality for other targets, setting them from xml (command line).
*my
Thanks
=> winrt adjust main compile and boot

src/nme/app/AppEvent.hx
Without this I get `/home/ibilon/Code/nme/src/nme/app/AppEvent.hx:40: characters 54-126 : Unsupported operation in cppia :CppCode`.
Not 100% sure about the fix.
=> Cppia compile fix

project/src/audio/SDLSound.cpp
On Mac latest xCode error:
error: ordered comparison between pointer and zero ('Mix_Music *' (aka '_Mix_Music *') and 'int')
if (mMusic>=0)
~~~~~~^ ~
1 error generated.
=> SDL sound compiler fix on Mac

.travis.yml
Travis CI has a cache feature, HXCPP_COMPILE_CACHE is a perfect candidate. In subsequent builds CI will be much faster! In my test commit this shaved 11m10s from the build!
https://docs.travis-ci.com/user/caching/#Arbitrary-directories
=> Cache the cache

tools/nme/src/CommandLineTools.hx
help compiling stablexui samples, such as 02first, with only "nme" shortcut (instead of "nme build.xml")
https://github.com/RealyUniqueName/StablexUI/tree/master/samples/02_first
=> add build.xml to findProjectFile

tools/run/RunMain.hx
When using the auto setup steps from git nme.
Seems like it's nme-toolkit and not nme-dev now? That's what travis uses, and it complained about the missing nme-toolkit for me.
Also I added some steps to build acadnme since it's needed for cppia.
=> nme-dev is now nme-toolkit and compile acadnme

templates/android/PROJ-gradle/app/build.gradle, templates/android/PROJ-gradle/gradle.properties, templates/android/extension-api/build.gradle, tools/nme/src/platforms/AndroidPlatform.hx
These fixes android build:
Using compileSdkVersion different of 26, 
Inverted slash in ANDROID_SDK, 
and commented out -Xmx1536m flag for gradle (JDK?) memory error.
=> Android -gradle compile fixes

templates/winrt/appx/AppxManifest.xml
Needs the Microsoft.VCLibs.140.00 or Microsoft.VCLibs.140.00.Debug
dependecy, otherwise crashes at startup because "vccorlib140_app.DLL" is
not found (used debugger/gflags to find out
https://stackoverflow.com/questions/36315538/how-to-determine-which-dll-dependency-is-failing-to-load-in-windows-store-univer/43128358#43128358
)
=> Add winrt VCLibs dependency

templates/android/java/org/haxe/nme/GameActivity.java, templates/android/java/org/haxe/nme/MainView.java
Fixes #590 
Android Life Cycle Diagram:
https://developer.android.com/guide/components/activities/activity-lifecycle#asem
GLSurfaceView mention of expected behavior during onStop:
https://developer.android.com/reference/android/opengl/GLSurfaceView.html#onPause()
=> [android] pause threads during onStop

templates/android/java/org/haxe/nme/GameActivity.java
Potential fix for #593 
It appears  that NME.popupKeyboard is getting called inside NME.onTouch.
When it is called, activity.mHandler is null.
The only time activity is set to null is in onDestroy. 
Since we cannot unsubscribe from `onTouchEvent` in MainView.java, let's add a null check.
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.os.Handler org.haxe.nme.GameActivity.mHandler' on a null object reference
at org.haxe.nme.GameActivity.popupKeyboard(GameActivity.java:1246)
at org.haxe.nme.NME.onTouch(NME.java)
at org.haxe.nme.MainView$6.run(MainView.java:410)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```
=> Null check for GLSurfaceOnTouch after onDestroy

tools/nme/src/CommandLineTools.hx, tools/nme/src/project/NMEProject.hx, tools/nme/src/project/NMMLParser.hx
Fixes https://github.com/haxenme/nme/issues/602.
Intent of "quickrun" command is to just build & run. It appears that skipping the asset compare & copy was missed. This diff properly skips that build step, this speeds up quickrun build by ~20 seconds in my project.
=> Fixes #602 quickrun is comparing assets

templates/android/PROJ-gradle/app/build.gradle, tools/nme/src/platforms/AndroidPlatform.hx, tools/nme/src/platforms/AndroidView.hx, tools/nme/src/project/NMEProject.hx, tools/nme/src/project/NMMLParser.hx
Fixes #601 
Fixes #604 
This diff changes the following behavior.
1) By default we build "armeabi-v7a", "arm64-v8a", and "x86" instead of just armeabi-v7a.
2) You can override this for faster builds by including one more more `<abi />` elements in your configurations.
```
<android>
<abi value="armeabi-v7a" />
<abi value="arm64-v8a" />
<abi value="x86" />
</android>
```
3) `android -gradle` build produces an APK for each architecture
4) `nme test android -gradle`install the APK by querying your device for it's architecture through adb
=> [android] ABI defaults, configuration, and multi APK support

templates/android/java/org/haxe/nme/GameActivity.java
Fixes #611
I get exceptions in this method often. I have a feeling it's related to onDestory not properly cleaning up. But it's difficult to track down the culprit. This is reproducible even in applications with out any native text use.
=> [android] popupKeyboard exception handling

src/nme/display/Graphics.hx
i've changed `Graphics.TILE_NO_ID` value from `0x0040` to `0x0080` (as in other places, like in [Tilesheet.hx](https://github.com/haxenme/nme/blob/master/src/nme/display/Tilesheet.hx#L17) and [ExternalInterface.cpp](https://github.com/haxenme/nme/blob/master/project/src/common/ExternalInterface.cpp#L2962))
=> Fix TILE_NO_ID value in Graphics.hx

project/src/android/JNI.cpp, src/nme/JNI.hx
Hello!
Our team is working on porting our project from old OpenFl legacy fork to NME (since it can generate 64-bit apk files). And some of our native extensions are using JNI.createStaticField() method, which is missing in Haxe part of NME (but cpp part of NME has it). So i thought it would be nice to add it back to NME again
=> add JNI.createStaticField method

templates/android/java/org/haxe/nme/MainView.java
- Fixes #631
- First did a `git revert 5f208aa898a35f1af03c537e8872cf422723b8d6`.
- Added a semaphore around the correct shared resource
Testing:
* Tested samples/DisplayingABitmap
* Tested samples/BunnyMark
=> [android] Fixes timertask race condition

project/src/audio/OpenSlSound.cpp
Simple fix to make sure sounds get their reference count decremented when OpenSL channels finish (otherwise they hung around in memory forever). This has been live on a large user base for 6 months or so and has helped reduce our crash rate pretty significantly so think it's good to go.
=> Add missing decref to OpenSLSound destructor, to prevent memory leak.

project/src/opengl/OGLExport.cpp
Mac GL version by default 2. Shader version can't be higher then 120 on GL 2.
=> Mac GL version fix

templates/android/java/org/haxe/nme/GameActivity.java
Fix for back button not working in Android >= 9 [#649](https://github.com/haxenme/nme/issues/649#issue-497695168)
=> Fix for issue #649

project/src/common/FreeType.cpp
This PR fix for https://github.com/haxenme/nme/issues/654 issue
Additional description:
Installed latest MacOS and lost default fonts _serif, _sans etc. Discovered that fonts moved to /System/Library/Fonts/Supplemental/ folder. Not sure if this unique to my case or on new mac fonts relocated. Can anybody confirm this?
=> More MacOS font folders

.gitignore, README.md, samples/Accelerometer/Source/README.md, samples/AppLinks/README.md, tools/nme/src/CommandLineTools.hx, tools/nme/src/project/NMEProject.hx
Fixes #655, if you still need ant then pass a `-ant` flag to NME.
Testing:
1. Rebuild the tools
2. Build a sample with `haxelib run nme test android`
Verified output is in gradle. (/)
=> [android] Make gradle the default android build tool

project/src/audio/OpenSlSound.cpp
As per https://github.com/haxenme/nme/issues/527 we've had this change live in our game since 2018 and it's reduced our crash rate by >50%. 
We're still not sure why it started happening on some Android devices in the first place (we've audited all our sounds to ensure they're encoded the same etc.), but when it comes to null checks it's sometime just better to be safe than sorry!
=> Add null checks around all uses of bqPlayerPlay in OpenSL

project/src/opengl/OGLExport.cpp, src/nme/gl/GL.hx
Updated from https://github.com/haxenme/nme/pull/518/files
Tested with 
```
var fragShader:String =
"precision mediump float;\n" +
"void main(){
// Output color = red
gl_FragColor = vec4(1.0,0.0,0.0,1.0);
}
";
var vertShader:String =
"precision mediump float;\n" +
"// Input vertex data, different for all executions of this shader.
uniform vec3 vertexPosition_modelspace;
void main(){
gl_Position.xyz = vertexPosition_modelspace;
gl_Position.w = 1.0;
}
";
var shaderProgram = nme.gl.Utils.createProgram(vertShader, fragShader);
var hlslSource =
nme.gl.GL.getTranslatedShaderSourceANGLE(shaderProgram.getShaders()[1]);
trace( ((hlslSource.split("// COMPILER INPUT HLSL BEGIN")[1]).split("// COMPILER INPUT HLSL END"))[0] );
```
Output
```
// GLSL
//
// #define texture texture2D// precision mediump …
```
=> getTranslatedShaderSourceANGLE implemented

templates/ios/UIStageView.mm
I am using Bluetooth mouse for iPad. Works on ios, ipados 13+. Could be useful for somebody too.  Android mouse move can be easily updated with:
case MotionEvent.ACTION_HOVER_MOVE:
//TODO process the mouse hover movement...
//Log.v("MainView","ACTION_HOVER_MOVE X:" + event.getRawX() + " Y:" + event.getRawY());
final MainView me1 = this;
final float x1 = event.getRawX();
final float y1 = event.getRawY();
queueEvent(new Runnable(){
public void run() { me1.HandleResult(NME.onMouseMove(x1,y1) ); }
});
return true; 
Mobile devices getting mouse friendly.
=> Initial mobile mouse support

templates/ios/UIStageView.mm
Issue description:
https://stackoverflow.com/questions/14122363/iphone-app-allow-background-music-to-continue-to-play
On older ios nme app can cancel background music when you open it, on new ios it will stop music when you close app.
=> iphone app allow background music to continue to play
