haxenme/nme

templates/ios/PROJ/PROJ-Info.plist, tests/haxe/test.sh, tools/nme/src/platforms/IOSPlatform.hx, tools/nme/src/project/NMEProject.hx, tools/nme/src/project/NMMLParser.hx
As part of integrating applovin(Opt in Video Adds) I needed to set custom ios properties.
```
<customIOSProperty key="AppLovinSdkKey" value="someSdkKey" />
```
=> Add custom IOS Properties with nmml.

nme/sensors/Accelerometer.hx, templates/android/PROJ/src/org/haxe/nme/GameActivity.java
I uncommented some code. We should just make an issue to move accelerometer off of the gui thread, I'm not sure how you'd like to go about doing that.
=> Fixed android accelerometer

nme/app/Window.hx
In old nme was global stage onkey event. If its good idea we can restore it for stage.window
=> onkey event

templates/android/PROJ/src/org/haxe/nme/GameActivity.java
1. backspace works on older android versions now
2. international keyboard characters (not only english, now can type other languages)
3. voice input
Tested on latest lollipop and old 4.4.2. Think still need more testing.
=> Android text input. part 1

project/src/android/AndroidFrame.cpp
I am using mouse for android tv.
Need support for mouse wheel. Works on android 4.4.2
=> Android mouse wheel support. part 1

project/src/common/FreeType.cpp
=> ios9 default fonts fix

README.md
Hi! I used NME today and I found it's quite hard to spot documentation on this project anywhere. Am I missing something? I added a really basic guide. I might be missing something on the build tool or dependencies, but this should be enough to get people up and running a bit faster than I did.
As a tip, I would love to see this being documented too:
- info on the build tool commands (what can you do)
- available options/settings in the config files
- documentation of hxcpp (you seem to need to install some stuff before it works?)
I used nme to test out waxe, (unfortunately also barely documented), but seems to be quite nice!! 
Keep up the good stuff.
=> basic installation info

README.md
I spent some time trying to make the readme a little more potent. It has also been per reviewed by @markknol
=> Worked on making the readme more concise and prettier.

templates/android/PROJ/src/org/haxe/nme/GameActivity.java
=> Activate enter key on android soft keyboard

project/src/iPhone/UIStageView.mm
Looks like this code make sence. It really fixed issue with dictation button app crash
=> iOS dictation button fix

nme/Vector.hx
Away3D using vectors a lot, trying to speed up this
=> Vector inline

project/ToolkitBuild.xml
Issue: https://github.com/haxenme/nme/issues/355
=> Fix for Toolkit compile issue

nme/display/Stage.hx
Fix https://github.com/haxenme/nme/issues/359
=> Fix fullscreen toggle

nme/app/EventName.hx, nme/app/Window.hx
Fix https://github.com/haxenme/nme/issues/362
=> Fix event names for joystick

templates/ios/PROJ.xcodeproj/project.pbxproj
=> ios camera support (1)

tools/nme/src/helpers/IconHelper.hx
Some icons where not displaying correctly. For example, when you place the cursor over the taskbar icon and a "preview" window appears, the default icon was shown instead of the game icon. Looking into various icons of Windows applications, I have found that they include the 8-bit versions of at least the sizes of 48, 32 and 16. Furthermore, none of them used the "96" size, so I removed it from the 32-bit versions. Also, they are written from larger to smaller (just changed the order in the array.  A warn message should be shown if the input image has more than 256 colors.  In that case we look for the nearest color that is already in the palette.  The algorithm may be improved, but actually is better design to use less than 255 colors anyway...  (no problem for the 16x16 icon which has …
=> Windows ICO: Add 8-bit images

nme/Assets.hx
Fixes https://github.com/haxenme/nme/issues/442
=> Fix initResources when using DCE (ios, static builds?)

nme/Lib.hx, nme/app/Application.hx, project/include/Display.h, project/src/sdl2/SDL2Stage.cpp, templates/haxe/ApplicationMain.hx, tools/nme/src/project/HxParser.hx, tools/nme/src/project/NMEProject.hx, tools/nme/src/project/Window.hx
Force only one instance of the game on Windows target.
Set in XML
```
<window singleInstance="true" />
```
NOTE: On mobile, singleInstance should be always true. For Windows, Mac and Linux is set to false as default (TODO: implement on Mac and Linux?)
=> [Windows] single instance proposal

nme/display/Stage.hx, nme/events/JoystickEvent.hx
This axis corresponds to the right-stick "up-down" axis.
"x" and "y" already correspond to the left-stick, and "z" to the
right-stick "left-right"
=> Enable "w" joystick axis in JoystickEvent

templates/ios/PROJ/PROJ-Info.plist
Try to fix https://github.com/haxenme/nme/issues/408
=> iOS DisplayName from Title

templates/android/PROJ/src/org/haxe/nme/GameActivity.java
Fix https://github.com/haxenme/nme/issues/421
=> Fix Android (19+) immersive mode (Capabilities and hide Navigation bar)

include.nmml, nme/app/Window.hx, nme/display/Stage.hx
Implement hxtelemetry.
Open hxscout and compile with "nme -DNME_HXTELEMETRY "
issue reference: https://github.com/haxenme/nme/issues/451
=> implement hxtelemetry

project/ToolkitBuild.xml, project/src/audio/Sound.cpp, project/src/common/ExternalInterface.cpp, project/src/common/Font.cpp, project/src/common/FreeType.cpp, project/src/common/Utils.cpp, project/src/sdl2/SDL2Stage.cpp, project/src/windows/CaptureDevice.cpp, project/src/windows/System.cpp
requires changes on nme-toolkit (angle and sdl)
https://github.com/native-toolkit/angle/pull/1
https://github.com/native-toolkit/sdl/pull/9
Edit: Also https://github.com/native-toolkit/png/pull/1
Compiles but has linking errors (TODO, needs to be a little similar to emscripten)
Edit: compiles but still getting linking errors from SDL
Edit: now compiling and linking including SDL
`nme -Dwinrt -DNME_ANGLE`
=> Initial winrt compile fixes

tools/nme/src/CommandLineTools.hx
Like you said it was indeed an easy fix ;)
Mac not tested but according to the internet that's how it's supposed to be run.
=> Run cppia build with acadnme on non windows

tools/nme/src/platforms/AndroidPlatform.hx
Tested it with nmml file settings:
<setenv name="PLATFORM" value="android-21" if="android"/>
<arch value="arm64" if="android"/>
<android minApiLevel="21" buildApiLevel="21" targetApiLevel="21"/>
=> arm64 android platform

templates/android/PROJ/src/org/haxe/nme/GameActivity.java
Fixes:
https://github.com/haxenme/nme/issues/325
=> Fix for selection text.

tools/nme/src/project/NMMLParser.hx
Use Access instead of Fast to avoid warnings in Haxe4
Reference: https://github.com/HeapsIO/heaps/commit/3a8665f500a46ea46917c5a7be341930c10540d2#diff-4a5c2339d519cfe0aa591b8c44a5fc44
=> handle haxe.xml.Access warnings

tools/nme/src/project/Dependency.hx
=> Fix to allow gradle only extensions to work.

README.md
=> Move most of readme to documentation site

README.md
This reverts commit bbf62b5a884a25e03489857aa0e1741b48bf55f4.
=> Revert "Move most of readme to documentation site"

project/src/common/ExternalInterface.cpp, project/src/opengl/OGL.h, project/src/opengl/OGLExport.cpp, project/src/opengl/OpenGLContext.cpp, src/nme/system/System.hx
Gets an int Array of GL statistics: vertex drawn and number of calls (0 Verts, 1 Calls, 2 Element Verts, 3 Element Calls).  See extension nme-stats for a sample: https://github.com/madrazo/nme-stats
=> Get GL Stats

project/src/common/ExternalInterface.cpp, src/nme/display/BitmapData.hx, src/nme/display/DirectRenderer.hx, src/nme/display/DisplayObjectContainer.hx, src/nme/display/Stage.hx, src/nme/display/Tilesheet.hx
Converting some functions.
Update from https://github.com/haxenme/nme/pull/515
=> Prime Functions for nme/display

src/nme/Vector.hx
For CPP target
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Vector.html
=> Resizable Vectot

project/src/android/JNI.cpp, src/nme/app/Window.hx
Fixes https://github.com/haxenme/nme/issues/581
=> Fix for prime loader regression in android. Fixes #581.

samples/Accelerometer/Source/Main.hx, samples/Accelerometer/Source/README.md, samples/Accelerometer/project.nmml, src/nme/sensors/Accelerometer.hx, src/nme/ui/Accelerometer.hx
=> Add accelerometer sample, and fix accelerometer bug.

tools/nme/src/project/NMMLParser.hx
Fixes #609 
Currently the order in which XML Is parsed determines how the final template folder will be populated. Confusion and problems can occur when you include extensions with templating. For example imagine you have this case.
```
nme/template/someFile.txt
someExtension/template/someFile.txt // <-- This file is instead used if the XML file is in a certain order
myProject/template/someFile.txt  // <-- Developer expects this file to be used
```
Testing:
=> Relational order templates

tools/nme/src/platforms/WinrtPlatform.hx
Get the newer SDK from directory name.
=> [winrt] Fix bin directory for newer Windows 10 SDKs

src/nme/events/TouchEvent.hx
MouseEvent cancelable and TouchEvent has to be similar.
=> Make TouchEvent cancelable

templates/android/java/org/haxe/nme/MainView.java
=> [android] Fix for rare race condition with timer.

project/src/opengl/OGLExport.cpp
I am still using GL 2, file GL.hx expecting function with one parameter
=> Minor old GL fix

samples/HandlingJoystickEvents/Source/Main.hx
Add missing retrieving buttons when using the "game input api"
=>  HandlingJoystickEvents sample, complete sample for NME_GAMEINPUT_API

src/nme/sensors/Accelerometer.hx
=> Avoid crash for unsupported accelerometer

src/nme/events/EventDispatcher.hx
Fix for issue https://github.com/haxenme/nme/issues/663
In case if we want make it similar to actionscript behavior.
=> Fix for #663

src/haxe/Timer.hx
=> simplify stoped timer remove

project/src/android/System.cpp
Fix for https://github.com/haxenme/nme/issues/691 issue
=> Clipboard fix on android

templates/ios/UIStageView.mm
We had a problem on iOS 13 (and only on this version) when our application crashed after unlocking device screen after some time (about 1 minute or so): the app crashes with `OpenGL resize failed` exception which occurs only in `createOGLFramebuffer` method.
I've googled info about potential source of the issue and found this [thread on Apple developers forum](https://developer.apple.com/forums/thread/23864). Suggested solution was to remove framebuffer update logic from layoutSublayers. So i've made similar changes in `UIStageView` and crash had gone. We also checked how it works on other iOS versions (12 and 14) and it works there fine too.
=> Fix crash on iOS 13 after screen device unlock

src/nme/app/Window.hx, src/nme/events/Event.hx
In case if we need close window evens, described here: https://github.com/haxenme/nme/issues/695
Update works well for secondary windows. I can even prevent window from closing using it.
=> Close window events

src/nme/net/HttpLoader.hx
Put isPost check outside of compiler conditional
=> Fix isPost check

templates/ios/UIStageView.mm
Tried this, Bluetooth mouse wheel now works on my ipad.
=> ios mouse wheel
